version: '3.8'

services:
  frontend:
    image: coopcred-frontend:1.0.0
    container_name: coopcred-frontend
    ports:
      - "8080:80"
    environment:
      BACKEND_URL: "http://44.204.138.207:3000"
    restart: unless-stopped