version: '3.8'

services:
  frontend:
    build: .
    container_name: coopcred-frontend
    ports:
      - "8080:80"
    environment:
      BACKEND_URL: "http://10.100.10:3000"
    restart: unless-stopped