version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:${KUMA_IMAGE_VERSION}
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "3001:3001"
    restart: always

volumes:
  uptime-kuma:
    name: uptime-kuma